### PR TITLE
Removed unnecessary stuff

### PR DESCRIPTION
**Pull request by TuomasBorman**
Hi,

**Beta**

-   I removed additional PERMANOVA test. Now, this beta diversity section is wrapped around PCoA --> additional components added (variables with coloring, and their associations with p-values)

**Unsupervised learning**

-   I removed that function that adds additional cluster for those features that were not clustered. That part was not actually even needed, because every feature was allocated to some cluster.

This changes make the material more simple, and we can focus on main topic

-Tuomas

### CODE REVIEW

**Review by ChouaibB — APPROVED** [review]

**Comment by ChouaibB** [comment]
Looks good! I will update the R files when this is merged.

**Comment by TuomasBorman** [comment]
How about this?

Cross-correlation part is a task. Those code chunks are hidden, so they are not included in material

After participants have done the task, solution is shown

After that, we move to biclustering part

**Comment by TuomasBorman** [comment]
@antagomir

**Comment by antagomir** [comment]
sounds good for now!

**Pull request merged**
