### PR TITLE
initial test

### PR DESCRIPTION
**Pull request by ChouaibB**
Testing if mofa2 works at GHA

### CODE REVIEW

**Review by TuomasBorman — APPROVED** [review]
Since this is now little bit more general (ot just cross-correlation), the title could be mutliomics and unsupervised learning instead of cross-corr and unsup

**Comment by TuomasBorman** [comment]
Also R files should be updated

**Comment by ChouaibB** [comment]
yes I am not sure if i can do it before the practicals, still working on mofa

**Comment by TuomasBorman** [comment]
> yes I am not sure if i can do it before the practicals, still working on mofa

OK, those R files are not that important. I change yesterday's r file

**Pull request merged**
